### ISSUE TITLE
Author not being displayed

### ISSUE THREAD

**Issue by PieEatingNinjas** [ordina-ncore/ordina-ncore.github.io#10]
The author of a blogpost is not being displayed.
If you take a look at my blogpost, you'll notice that at the bottom my information isn't being displayed. 
https://ordina-ncore.github.io/conferences/2017/05/31/pieter-nijs-techorama-2017.html

Can somebody see what is off?

**Comment by jensg** [comment]
Problem seems to be related with _plugins/hooks/site/post_read/post_enricher.rb

**Comment by jensg** [comment]
None of the plugins are executed:
_plugins/author_page_generator.rb
_plugins/category_page_generator.rb
_plugins/hooks/site/post_read/author_enricher.rb
_plugins/hooks/site/post_read/post_enricher.rb
_plugins/tag_page_generator.rb

**Comment by gertjanvanthienen** [comment]
more detail here:

https://github.com/jekyll/jekyll/issues/325

**Comment by timhulstaert** [comment]
fixed
