### ISSUE TITLE
Youtube link points to jworks youtube

### ISSUE THREAD

**Issue by gertjanvanthienen** [ordina-ncore/ordina-ncore.github.io#12]
The youtube link on the blog's homepage points to https://ordina-ncore.github.io/youtube

which redirects to the wrong youtube

**Comment by jensg** [comment]
What is the correct youtube? What do you suggest? Removing it? Fixing the url?

**Comment by gertjanvanthienen** [comment]
I don't think we already have a youtube ourselves.

I suggest to remove the link from the homepage until we created one.

**Comment by jorgen-jacob** [comment]
I would link to https://www.youtube.com/channel/UCYP5uoJpDFU4v47ElI_k6xg
which is the Ordina Belgium Youtube channel for now, until we have our own channel
