### ISSUE TITLE
Categories and tags links do not work - 404

### ISSUE THREAD

**Issue by jorgen-jacob** [ordina-ncore/ordina-ncore.github.io#13]
When clicking on e.g. categories you get a 404 page
It links to https://ordina-ncore.github.io/categories/conferences
![capture404- categories and tags do not work](https://cloud.githubusercontent.com/assets/17164053/26755236/a7fed780-4889-11e7-88bd-22e226a6d018.PNG)

**Comment by jensg** [comment]
This has the same cause: 
https://github.com/ordina-ncore/ordina-ncore.github.io/issues/10#issuecomment-305974630
Plugins are not executed when code is pushed, some pages are not generated because of that.

**Comment by timhulstaert** [comment]
fixed
