### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by jensg** [ordina-ncore/ordina-ncore.github.io#35]
Mathias reported the following issue:
![image](https://user-images.githubusercontent.com/3176346/31711142-8774e9da-b3f7-11e7-8a1a-0f06ddfb5a74.png)

**Comment by JeroenRombouts** [comment]
I'm assuming he means that there is no scroll bar in the modal? Or that the modal doesn't adjust to the text size? Or to the abstract being too long? ;)

I'll add an overflow property to the css when I get home tonight.

**Comment by mathiasschaemelhout** [comment]
@JeroenRombouts  The main issue was indeed the absence of the scrollbar in the modal.
Thanks!

**Comment by JeroenRombouts** [comment]
Done. Can you check and close?

**Comment by JeroenRombouts** [comment]
@Schaemelhout no reaction => closed.

**Comment by mathiasschaemelhout** [comment]
Was waiting for issue author to close because the issue is fixed.
Thanks for the effort!
